services:
  # rabbitmq:
  #   image: "rabbitmq:3-management"
  #   container_name: "rabbitmq"
  #   hostname: "rabbitmq"
  #   environment:
  #     RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
  #     RABBITMQ_DEFAULT_USER: "guest"
  #     RABBITMQ_DEFAULT_PASS: "guest"
  #     RABBITMQ_DEFAULT_VHOST: "/"
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  #   labels:
  #     NAME: "rabbitmq"

  trip-service:
    container_name: trip-service
    build:
      context: .
      dockerfile: ./infra/development/docker/go.Dockerfile
      args:
        - SERVICE_NAME=trip-service
    # ports:
    #   - 7001:9000
    # depends_on:
    #   - rabbitmq
    networks:
      - rabbitmq
      - internal
    volumes:
      - ./services/trip-service/:/data/services/trip-service/
      - ./shared/:/data/shared/

  driver-service:
    # container_name: driver-service
    # hostname: driver-service
    build:
      context: .
      dockerfile: ./infra/development/docker/go.Dockerfile
      args:
        - SERVICE_NAME=driver-service
    # deploy:
    #   replicas: 1
    # ports:
    #   - 7002:9000
    # depends_on:
    #   - rabbitmq
    networks:
      - rabbitmq
      - internal
    volumes:
      - ./services/driver-service/:/data/services/driver-service/
      - ./shared/:/data/shared/

  payment-service:
    build:
      context: .
      dockerfile: ./infra/development/docker/go.Dockerfile
      args:
        - SERVICE_NAME=payment-service
    networks:
      - rabbitmq
      - internal
    volumes:
      - ./services/payment-service/:/data/services/payment-service/
      - ./shared/:/data/shared/
    env_file:
      - ./.env

  api-gateway:
    container_name: api-gateway
    depends_on:
      - trip-service
      - driver-service
      - payment-service
    build:
      context: .
      dockerfile: ./infra/development/docker/go.Dockerfile
      args:
        - SERVICE_NAME=api-gateway
    ports:
      - 7000:7000
    networks:
      - internal
      - rabbitmq
    volumes:
      - ./services/api-gateway/:/data/services/api-gateway/
      - ./shared/:/data/shared/

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./infra/development/docker/web.Dockerfile
    depends_on:
      - api-gateway
    ports:
      - 3000:3000
    networks:
      - internal
    volumes:
      - ./web/src:/app/src

networks:
  internal:
    name: internal
    driver: bridge
  rabbitmq:
    external: true
